basic files creation and deletion. .editconfig added. react-redux and…
CornetS28/book-management pull request #1
Opened 2019-11-26 18:28 UTC by CornetS28

Book Management App
- create-react-app created the basic files
- Redux and react-redux was added
- .editorcnfig file was added

2019-11-27 11:34 UTC, BalintMendli requested changes
Hi @CornetS28 ,

Great job setting up the project.

However, we need to take care of some things before moving on:
- `redux` and `react-redux` should be under `dependencies` instead of `devDependencies` as they are required at runtime not just during development.
- Let's set up Stickler on the repo. Instructions [here](https://github.com/microverseinc/linters-config/tree/master/react-redux).
- We can remove unnecessary files which are not needed for this project, like `serviceWorker.js` and also `App.test.js` unless you plan to write tests for the project.
- Please add a descriptive readme

**Please update the app and submit another review request.**

2019-11-27 14:27 UTC, CornetS28 commented
> Hi @CornetS28 ,
> 
> Great job setting up the project.
> 
> However, we need to take care of some things before moving on:
> 
> * `redux` and `react-redux` should be under `dependencies` instead of `devDependencies` as they are required at runtime not just during development.
> * Let's set up Stickler on the repo. Instructions [here](https://github.com/microverseinc/linters-config/tree/master/react-redux).
> * We can remove unnecessary files which are not needed for this project, like `serviceWorker.js` and also `App.test.js` unless you plan to write tests for the project.
> * Please add a descriptive readme
> 
> **Please update the app and submit another review request.**

Thank you for your feedback!

2019-11-27 16:54 UTC, SunnyAsar requested changes
# Hi @CornetS28 👋 
Well done with the project setup, for the finish, please install the required packages.

**Please request another review with the update**

2019-11-27 16:54 UTC, SunnyAsar commented on README.md
> +
please clean up this file. let your `readme` be project specific and not the default provided by react. Add things like the setup info, contributor(s) etc.

2019-11-27 16:54 UTC, SunnyAsar commented on package.json
> +    "react-route-hook": "^1.2.1",
we don't need some of these for this project. here are the requirements from pathwrite.

![AddReduxAndReact-Redux](https://user-images.githubusercontent.com/10922508/69742759-96dd8a80-113d-11ea-817a-5c1a659a45a0.png)

2019-11-28 08:57 UTC, SunnyAsar requested changes
# Hi @CornetS28 
Please check the linting errors in the code and make corrections.

**Please request another review when done**

2019-11-28 08:57 UTC, SunnyAsar commented on src/index.js
> +import React from "react";
let's fix the linting errors.

2019-11-28 14:51 UTC, shloch approved these changes
## Nice job, @CornetS28 

for next milestones, make branch names to be descriptive, something like `milestone-2-addingDisplay` 

### You can merge this PR 👏👏👏

2019-11-28 15:30 UTC, merged