Milestone 2 adding display
CornetS28/book-management pull request #2
Opened 2019-11-29 22:15 UTC by CornetS28

What I have accomplished:

- Actions, components, containers, and reducers files created,
- A default booklist was created,
- Books actions were put in actions/index,js file,
-  Book  and book form component in Components directory,
- BookList is put in containers/BooksList,js file, and
- App,js wrap up BooksList and BooksForm

2019-12-02 10:11 UTC, shloch requested changes
Hello @CornetS28 ;

The project is perfectly executed. I just need you to bring minor changes linked to relocating files and probably adjusting import statements. No problem with logic at all 


Just finish this and file for a re-review........... (after this this, we're already ready for next milestone)

2019-12-02 10:11 UTC, shloch commented on src/components/BooksForm.js
> +    <option key={cat} value={cat}>
since the Form is a container, please relocate this file into the `src/containers/` directory

2019-12-02 10:11 UTC, shloch commented on src/App.js
> +import BooksForm from './components/BooksForm';
this is normally fine, but for the sake of the requirements of this project, please relocate this file into the `src/components/` folder

2019-12-03 21:50 UTC, CornetS28 commented
What I did:
- As recommended, I have relocated (should I say again) BookslList to containers.

**Notice:** I have been receiving feedback from several code-reviewers for the same pull request. For instance, I have received 2 feedback from 2 different TSE. You told me to relocate my BooksList file into containers (which I have done before your 1st feedback) and another TSE send me feedback and told me that milestone 2 is approved. It is very confusing! Also, for the 1st milestone, I have received feedback from at least 4 TSE for the same pull request. Again, it is confusing. Is there a bug in the system that needs to be taking care of? If so, please report it.

2019-12-04 10:35 UTC, shloch commented
There should be a bug...sorry about that

2019-12-04 10:38 UTC, shloch approved these changes
## Hello @CornetS28 ,

You can merge this PR request.....don't worry about other reviews, must have been a bug

### Nice job...Happy coding bro 🎅🎅🎅

2019-12-05 19:03 UTC, merged